/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "RedirectFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "RedirectRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Studio": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "WebVitals": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Website": {
      "type": "sst.aws.Remix"
      "url": string
    }
  }
}
